### ISSUE TITLE
请问如何控制页面跳转？

### ISSUE THREAD

**Issue by 2yunyun** [agileago/webpack-mutiple#6]
多个路由吗？

**Comment by agileago** [comment]
什么叫控制页面跳转？ 每个页面是个单独的html，html之间跳转就靠url

**Comment by 2yunyun** [comment]
有例子吗

**Comment by 2yunyun** [comment]
比如Home页有个底部导航栏（有首页和我的两项），点击切换到‘我的’页面，咋实现呢？
有时间麻烦解答一下，改为多页面后我就蒙圈了。。。。
谢谢！

**Comment by 2yunyun** [comment]
明白了，谢谢！
